/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bikerental;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author firstx
 */
public class FormManageBike extends javax.swing.JFrame implements FormTableInterface {

    private final ServiceManageBike service;
    private DefaultTableModel model;

    /**
     * Creates new form FromManageBike
     */
    public FormManageBike() {
        initComponents();
        service = new ServiceManageBike();
        renderTable();
        model = (DefaultTableModel) tableBike.getModel();
        showDate();
        showTime();
    }

    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        labelShowDate.setText(s.format(d));

    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                labelShowTime.setText(s.format(d));
            }

        }
        ).start();
    }

    public boolean isFill(String field) {
        return !field.equals("");
    }

    public boolean isFieldAllFill() {
        return isFill(txtBikeId.toString());
    }

    private boolean checkSelectedRow() {
        int rowIndex = tableBike.getSelectedRow();
        return rowIndex != -1;
    }

    private void add() {
        if (isFieldAllFill()) {
            Bike bike = new Bike(txtBikeId.getText(), txtBikeStatus.getText());
            if (service.addBike(bike)) {
                clear();
                alertMessage("เพิ่มข้อมูลรถสำเร็จ");
                renderTable();

            } else {
                alertMessage("มีรหัสรถคันนี้อยู่แล้วในระบบ");
                clear();
            }
        } else {
            alertMessage("กรุณากรอกข้อมูลให้ครบถ้วน");
            clear();

        }
    }

    private void remove() {
        if (checkSelectedRow()) {
            int rowIndex = tableBike.getSelectedRow();
            String bikeId = tableBike.getValueAt(rowIndex, 0).toString();
            if (service.removeBikeById(bikeId)) {
                alertMessage("ลบข้อมูลรถสำเร็จ");
                renderTable();
                clear();
            } else {
                alertMessage("ลบข้อมูลรถไม่สำเร็จ");
                clear();
            }
        } else {
            alertMessage("กรุณาเลือกรถที่ต้องการลบในตาราง");
            clear();
        }
    }

    private void search() {
        try {
            Bike cursor = service.findBikeById(txtSearch.getText());

             String[] column = {"รหัสรถ", "สถานะ"};
        tableBike.getTableHeader().setFont(new Font("TH Sarabun New", Font.BOLD, 18));

            DefaultTableModel model = new DefaultTableModel(column, 0);
            Bike bike = cursor;
            String bikeId = bike.getBikeId();
            String bikeStatus = bike.getBikeStatus();
            model.addRow(new Object[]{bikeId, bikeStatus});

            tableBike.setModel(model);
        } catch (Exception e) {
            alertMessage("ไม่พบรหัสรถคันนี้ในระบบ");
            renderTable();
            clear();
        }
    }

    private void searchAll() {
        renderTable();
        txtSearch.setText("");
        clear();
    }

    public void clear() {
        txtBikeId.setText("");
        txtSearch.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBike = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBikeId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bt_add = new javax.swing.JButton();
        bt_del = new javax.swing.JButton();
        txtBikeStatus = new javax.swing.JTextField();
        bt_get1 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        bt_se = new javax.swing.JButton();
        bt_all = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        head = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelShowTime = new javax.swing.JLabel();
        labelShowDate = new javax.swing.JLabel();
        line = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuMainMenu = new javax.swing.JMenu();
        menuBikeInfo = new javax.swing.JMenu();
        menuCusInfo = new javax.swing.JMenu();
        menuEmployeeInfo = new javax.swing.JMenu();
        menuRentBike = new javax.swing.JMenu();
        menuReturnBike = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ข้อมูลรถ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(840, 330));

        tableBike.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        tableBike.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBikeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBike);

        jLabel2.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        jLabel2.setText("รหัสรถ :");

        txtBikeId.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        txtBikeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBikeIdActionPerformed(evt);
            }
        });
        txtBikeId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBikeIdKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        jLabel6.setText("สถานะ :");

        bt_add.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        bt_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        bt_add.setText("เพิ่ม");
        bt_add.setBorderPainted(false);
        bt_add.setContentAreaFilled(false);
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        bt_del.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        bt_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        bt_del.setText("ลบ");
        bt_del.setBorderPainted(false);
        bt_del.setContentAreaFilled(false);
        bt_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_delActionPerformed(evt);
            }
        });

        txtBikeStatus.setEditable(false);
        txtBikeStatus.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        txtBikeStatus.setText("ว่าง");
        txtBikeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBikeStatusActionPerformed(evt);
            }
        });

        bt_get1.setFont(new java.awt.Font("DB Narai X", 0, 18)); // NOI18N
        bt_get1.setForeground(new java.awt.Color(255, 51, 51));
        bt_get1.setText("ล้างข้อมูล");
        bt_get1.setBorder(null);
        bt_get1.setBorderPainted(false);
        bt_get1.setContentAreaFilled(false);
        bt_get1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_get1ActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("DB Narai X", 0, 18)); // NOI18N
        txtSearch.setToolTipText("");
        txtSearch.setName(""); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        bt_se.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        bt_se.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        bt_se.setText("ค้นหา");
        bt_se.setBorderPainted(false);
        bt_se.setContentAreaFilled(false);
        bt_se.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_seActionPerformed(evt);
            }
        });

        bt_all.setBackground(new java.awt.Color(255, 255, 255));
        bt_all.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        bt_all.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/all.png"))); // NOI18N
        bt_all.setText("ดูทั้งหมด");
        bt_all.setBorderPainted(false);
        bt_all.setContentAreaFilled(false);
        bt_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_allActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("DB Narai X", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*กรอกไอดีรถที่ต้องการค้นหา");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(10, 10, 10)
                .addComponent(bt_se, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_all, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addComponent(txtBikeId, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(bt_get1)
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addComponent(txtBikeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(bt_add))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(660, 660, 660)
                .addComponent(bt_del))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel10))
                    .addComponent(bt_se, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_all, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtBikeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bt_get1))
                    .addComponent(jLabel6)
                    .addComponent(txtBikeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_add))
                .addGap(8, 8, 8)
                .addComponent(bt_del))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 890, 400));

        head.setBackground(new java.awt.Color(255, 255, 255));
        head.setPreferredSize(new java.awt.Dimension(902, 600));
        head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("DB Narai X", 1, 36)); // NOI18N
        jLabel9.setText("RENTAL CARS");
        head.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        head.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 88, 72));

        labelShowTime.setFont(new java.awt.Font("DB Narai X", 1, 18)); // NOI18N
        labelShowTime.setText("HH:MM:SS A");
        head.add(labelShowTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        labelShowDate.setFont(new java.awt.Font("DB Narai X", 1, 18)); // NOI18N
        labelShowDate.setText("dd-MM-yyyy");
        head.add(labelShowDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 90));

        line.setBackground(new java.awt.Color(238, 88, 40));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 890, -1));

        menuBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 51, 0), 1, true));
        menuBar.setEnabled(false);

        menuMainMenu.setBorder(null);
        menuMainMenu.setText("เมนูหลัก");
        menuMainMenu.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMainMenuMouseClicked(evt);
            }
        });
        menuBar.add(menuMainMenu);

        menuBikeInfo.setBorder(null);
        menuBikeInfo.setText("ข้อมูลรถ");
        menuBikeInfo.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuBikeInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBikeInfoMouseClicked(evt);
            }
        });
        menuBar.add(menuBikeInfo);

        menuCusInfo.setText("ข้อมูลลูกค้า");
        menuCusInfo.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuCusInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCusInfoMouseClicked(evt);
            }
        });
        menuBar.add(menuCusInfo);

        menuEmployeeInfo.setBorder(null);
        menuEmployeeInfo.setText("ข้อมูลพนักงาน");
        menuEmployeeInfo.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuEmployeeInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEmployeeInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuEmployeeInfoMouseEntered(evt);
            }
        });
        menuBar.add(menuEmployeeInfo);

        menuRentBike.setBorder(null);
        menuRentBike.setText("การเช่า");
        menuRentBike.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuRentBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuRentBikeMousePressed(evt);
            }
        });
        menuBar.add(menuRentBike);

        menuReturnBike.setBorder(null);
        menuReturnBike.setText("การคืน");
        menuReturnBike.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuReturnBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuReturnBikeMousePressed(evt);
            }
        });
        menuBar.add(menuReturnBike);

        menuLogout.setBorder(null);
        menuLogout.setText("ออกจากระบบ");
        menuLogout.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuLogoutMousePressed(evt);
            }
        });
        menuBar.add(menuLogout);

        setJMenuBar(menuBar);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableBikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBikeMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tableBikeMouseClicked

    private void txtBikeIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBikeIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBikeIdKeyReleased

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:
        if (isFill(txtBikeId.getText())) {
            add();
        } else {
            alertMessage("กรุณากรอกข้อมูลให้ครบถ้วน");
        }

    }//GEN-LAST:event_bt_addActionPerformed

    private void bt_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_delActionPerformed
        // TODO add your handling code here:
        remove();
    }//GEN-LAST:event_bt_delActionPerformed

    private void bt_get1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_get1ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_bt_get1ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void bt_seActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_seActionPerformed
        // TODO add your handling code here:
        if (!isFill(txtSearch.getText())) {
            System.out.println("ไม่กรอก");
        } else {
            search();
        }
    }//GEN-LAST:event_bt_seActionPerformed

    private void bt_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_allActionPerformed
        // TODO add your handling code here:

        searchAll();

    }//GEN-LAST:event_bt_allActionPerformed

    private void txtBikeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBikeStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBikeStatusActionPerformed

    private void menuMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMainMenuMouseClicked
        new FormBikeStatus().show();
        dispose();
    }//GEN-LAST:event_menuMainMenuMouseClicked

    private void menuBikeInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBikeInfoMouseClicked
        // TODO add your handling code here:
        new FormManageBike().show();
        dispose();
    }//GEN-LAST:event_menuBikeInfoMouseClicked

    private void menuCusInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCusInfoMouseClicked
        // TODO add your handling code here:
        new FormShowCustomer().show();
        dispose();
    }//GEN-LAST:event_menuCusInfoMouseClicked

    private void menuEmployeeInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEmployeeInfoMouseClicked
        // TODO add your handling code here:
        new FormManageEmployee().show();
        dispose();

    }//GEN-LAST:event_menuEmployeeInfoMouseClicked

    private void menuEmployeeInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEmployeeInfoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEmployeeInfoMouseEntered

    private void menuRentBikeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRentBikeMousePressed
        // TODO add your handling code here:
        new FormRent().show();
        dispose();
    }//GEN-LAST:event_menuRentBikeMousePressed

    private void menuReturnBikeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReturnBikeMousePressed
        new FormReturn().show();
        dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_menuReturnBikeMousePressed

    private void menuLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMousePressed

        // TODO add your handling code here:*/
    }//GEN-LAST:event_menuLogoutMousePressed

    private void txtBikeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBikeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBikeIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormManageBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormManageBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormManageBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormManageBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormManageBike().setVisible(true);
                FormManageBike f = new FormManageBike();
                
                System.out.println(f.isFill(""));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_all;
    private javax.swing.JButton bt_del;
    private javax.swing.JButton bt_get1;
    private javax.swing.JButton bt_se;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelShowDate;
    private javax.swing.JLabel labelShowTime;
    private javax.swing.JPanel line;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBikeInfo;
    private javax.swing.JMenu menuCusInfo;
    private javax.swing.JMenu menuEmployeeInfo;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuMainMenu;
    private javax.swing.JMenu menuRentBike;
    private javax.swing.JMenu menuReturnBike;
    private javax.swing.JTable tableBike;
    private javax.swing.JTextField txtBikeId;
    private javax.swing.JTextField txtBikeStatus;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void renderTable() {
        List<Bike> bikeList = service.findAllBike();
        Iterator<Bike> cursor = bikeList.iterator();

        String[] column = {"รหัสรถ", "สถานะ"};
        tableBike.getTableHeader().setFont(new Font("TH Sarabun New", Font.BOLD, 18));

        model = new DefaultTableModel(column, 0);

        try {
            while (cursor.hasNext()) {
                Bike bike = cursor.next();
                String bikeId = bike.getBikeId();
                String bikeStatus = bike.getBikeStatus();
                model.addRow(new Object[]{bikeId, bikeStatus});
            }
        } finally {

        }
        tableBike.setModel(model);
    }

    @Override
    public void alertMessage(String message) {
        JLabel label = new JLabel(message);
        label.setFont(new Font("TH Sarabun New", Font.BOLD, 18));
        JOptionPane.showMessageDialog(null, label, "แจ้งเตือน", JOptionPane.DEFAULT_OPTION);
    }
}
