/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bikerental;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author firstx
 */
public class FormManageEmployee extends javax.swing.JFrame implements FormTableInterface {

    private final ServiceManageEmployee service;
    private DefaultTableModel model;

    /**
     * Creates new form FromManageEmployee
     */
    public FormManageEmployee() {
        initComponents();
        service = new ServiceManageEmployee();
        model = (DefaultTableModel) tableEmployee.getModel();
        renderTable();
        showDate();
        showTime();
    }
    
         void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        labelShowDate.setText(s.format(d));

    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                labelShowTime.setText(s.format(d));
            }

        }
        ).start();
    }

    public boolean isFill(String field) {
        return !field.equals("");
    }

    public boolean isFieldAllFill() {
        return isFill(txtId.getText())
                && isFill(txtPassword.getText());
    }

    private boolean checkSelectedRow() {
        int rowIndex = tableEmployee.getSelectedRow();
        return rowIndex != -1;
    }

    private void add() {
        if (isFieldAllFill()) {
            String id = txtId.getText();
            String password = txtPassword.getText();
            String role = combo_level.getSelectedItem().toString();
            if(role.equals("ผู้ดูแลระบบ")){
                role = "Admin";
            } else if(role.equals("พนักงาน")) {
                role = "Employee";
            }
            Employee employee = new Employee(id, password, role);
            if (service.addEmployee(employee)) {
                alertMessage("เพิ่มข้อมูลพนักงานสำเร็จ");
                renderTable();
                clear();
            } else {
                alertMessage("มีชื่อผู้ใช้งานนี้อยู่แล้วในระบบ");
                clear();
            }
        } else {
            alertMessage("กรุณากรอกข้อมูลให้ครบถ้วน");
            clear();
        }
    }

    private void remove() {
        if (checkSelectedRow()) {
            int rowIndex = tableEmployee.getSelectedRow();
            String employeeId = model.getValueAt(rowIndex, 0).toString();
            if (service.removeEmployeeById(employeeId)) {
                alertMessage("ลบพนักงานสำเร็จ");
                renderTable();
                clear();
            } else {
                alertMessage("ผิดพลาด");
                clear();
            }
        } else {
            alertMessage("กรุณาเลือกพนักงานที่ต้องการลบในตาราง");
        }
    }

    public void changePassword() {
        if (isFieldAllFill()) {
            String employeeId = txtId.getText();
            String employeePassword = txtPassword.getText();
            Employee newEmployee = new Employee();
            newEmployee.setEmployeeId(employeeId);
            newEmployee.setPassword(employeePassword);
            if (service.findEmployeeById(employeeId) != null) {
                if (service.editEmployeeById(employeeId, newEmployee)) {
                    alertMessage("เปลี่ยนรหัสผ่านสำเร็จ");
                    renderTable();
                    clear();
                } else {
                    alertMessage("เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง!");
                    clear();
                }
            } else {
                alertMessage("ไม่พบรหัสผู้ใช้งานนี้อยู่ในระบบ");
            }
        } else {
            alertMessage("กรุณากรอกข้อมูลให้ครบถ้วน");
        }
    }

    public void clear() {
        txtId.setText("");
        txtPassword.setText("");
        txtSearch.setText("");
    }

    public void searchAll() {
        renderTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        line = new javax.swing.JPanel();
        head = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelShowTime = new javax.swing.JLabel();
        labelShowDate = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmployee = new javax.swing.JTable();
        bt_addemp = new javax.swing.JButton();
        bt_del = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        combo_level = new javax.swing.JComboBox<>();
        bt_edit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        bt_se = new javax.swing.JButton();
        bt_all = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuMainMenu = new javax.swing.JMenu();
        menuBikeInfo = new javax.swing.JMenu();
        menuCusInfo = new javax.swing.JMenu();
        menuEmployeeInfo = new javax.swing.JMenu();
        menuRentBike = new javax.swing.JMenu();
        menuReturnBike = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ข้อมูลพนักงาน");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        line.setBackground(new java.awt.Color(238, 88, 40));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 880, -1));

        head.setBackground(new java.awt.Color(255, 255, 255));
        head.setPreferredSize(new java.awt.Dimension(902, 600));
        head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("DB Narai X", 1, 36)); // NOI18N
        jLabel9.setText("RENTAL CARS");
        head.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        head.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 88, 72));

        labelShowTime.setFont(new java.awt.Font("DB Narai X", 1, 18)); // NOI18N
        labelShowTime.setText("HH:MM:SS A");
        head.add(labelShowTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        labelShowDate.setFont(new java.awt.Font("DB Narai X", 1, 18)); // NOI18N
        labelShowDate.setText("dd-MM-yyyy");
        head.add(labelShowDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableEmployee.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        tableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEmployee);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 780, 240));

        bt_addemp.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        bt_addemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        bt_addemp.setText("เพิ่ม");
        bt_addemp.setBorderPainted(false);
        bt_addemp.setContentAreaFilled(false);
        bt_addemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addempActionPerformed(evt);
            }
        });
        jPanel1.add(bt_addemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 128, 64));

        bt_del.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        bt_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        bt_del.setText("ลบ");
        bt_del.setBorderPainted(false);
        bt_del.setContentAreaFilled(false);
        bt_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_delActionPerformed(evt);
            }
        });
        jPanel1.add(bt_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 143, 50));

        txtId.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 188, 35));

        txtPassword.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 188, 35));

        combo_level.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        combo_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "พนักงาน", "ผู้ดูแลระบบ" }));
        combo_level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_levelActionPerformed(evt);
            }
        });
        jPanel1.add(combo_level, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        bt_edit.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        bt_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        bt_edit.setText("เปลี่ยนรหัสผ่าน");
        bt_edit.setBorderPainted(false);
        bt_edit.setContentAreaFilled(false);
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editActionPerformed(evt);
            }
        });
        jPanel1.add(bt_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 248, 50));

        jLabel2.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        jLabel2.setText("ชื่อผู้ใช้งาน :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 95, -1));

        jLabel3.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        jLabel3.setText("รหัสผ่าน :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 95, -1));

        jLabel4.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        jLabel4.setText("สถานะ :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 69, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        txtSearch.setFont(new java.awt.Font("DB Narai X", 0, 18)); // NOI18N
        txtSearch.setToolTipText("");
        txtSearch.setName(""); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 450, 30));

        bt_se.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        bt_se.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        bt_se.setText("ค้นหา");
        bt_se.setBorderPainted(false);
        bt_se.setContentAreaFilled(false);
        bt_se.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_seActionPerformed(evt);
            }
        });
        jPanel1.add(bt_se, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 100, 40));

        bt_all.setBackground(new java.awt.Color(255, 255, 255));
        bt_all.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        bt_all.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/all.png"))); // NOI18N
        bt_all.setText("ดูทั้งหมด");
        bt_all.setBorderPainted(false);
        bt_all.setContentAreaFilled(false);
        bt_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_allActionPerformed(evt);
            }
        });
        jPanel1.add(bt_all, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 880, 440));

        menuBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 51, 0), 1, true));
        menuBar.setEnabled(false);

        menuMainMenu.setBorder(null);
        menuMainMenu.setText("เมนูหลัก");
        menuMainMenu.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMainMenuMouseClicked(evt);
            }
        });
        menuBar.add(menuMainMenu);

        menuBikeInfo.setBorder(null);
        menuBikeInfo.setText("ข้อมูลรถ");
        menuBikeInfo.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuBikeInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBikeInfoMouseClicked(evt);
            }
        });
        menuBar.add(menuBikeInfo);

        menuCusInfo.setText("ข้อมูลลูกค้า");
        menuCusInfo.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuCusInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCusInfoMouseClicked(evt);
            }
        });
        menuBar.add(menuCusInfo);

        menuEmployeeInfo.setBorder(null);
        menuEmployeeInfo.setText("ข้อมูลพนักงาน");
        menuEmployeeInfo.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuEmployeeInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEmployeeInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuEmployeeInfoMouseEntered(evt);
            }
        });
        menuBar.add(menuEmployeeInfo);

        menuRentBike.setBorder(null);
        menuRentBike.setText("การเช่า");
        menuRentBike.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuRentBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuRentBikeMousePressed(evt);
            }
        });
        menuBar.add(menuRentBike);

        menuReturnBike.setBorder(null);
        menuReturnBike.setText("การคืน");
        menuReturnBike.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuReturnBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuReturnBikeMousePressed(evt);
            }
        });
        menuBar.add(menuReturnBike);

        menuLogout.setBorder(null);
        menuLogout.setText("ออกจากระบบ");
        menuLogout.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuLogoutMousePressed(evt);
            }
        });
        menuBar.add(menuLogout);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEmployeeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableEmployeeMouseClicked

    private void bt_addempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addempActionPerformed
        // TODO add your handling code here:
        add();

    }//GEN-LAST:event_bt_addempActionPerformed

    private void bt_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_delActionPerformed
        // TODO add your handling code here:
        remove();
    }//GEN-LAST:event_bt_delActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void bt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editActionPerformed
        // TODO add your handling code here:
        changePassword();
    }//GEN-LAST:event_bt_editActionPerformed

    private void menuMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMainMenuMouseClicked
        new FormBikeStatus().show();
        dispose();
    }//GEN-LAST:event_menuMainMenuMouseClicked

    private void menuBikeInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBikeInfoMouseClicked
        // TODO add your handling code here:
        new FormManageBike().show();
        dispose();
    }//GEN-LAST:event_menuBikeInfoMouseClicked

    private void menuCusInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCusInfoMouseClicked
        // TODO add your handling code here:
        new FormShowCustomer().show();
        dispose();
    }//GEN-LAST:event_menuCusInfoMouseClicked

    private void menuEmployeeInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEmployeeInfoMouseClicked
        // TODO add your handling code here:
        new FormManageEmployee().show();
        dispose();

    }//GEN-LAST:event_menuEmployeeInfoMouseClicked

    private void menuEmployeeInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEmployeeInfoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEmployeeInfoMouseEntered

    private void menuRentBikeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRentBikeMousePressed
        // TODO add your handling code here:
        new FormRent().show();
        dispose();
    }//GEN-LAST:event_menuRentBikeMousePressed

    private void menuReturnBikeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReturnBikeMousePressed
        new FormReturn().show();
        dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_menuReturnBikeMousePressed

    private void menuLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMousePressed

        // TODO add your handling code here:*/
    }//GEN-LAST:event_menuLogoutMousePressed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void bt_seActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_seActionPerformed
        // TODO add your handling code here:
        if (!isFill(txtSearch.getText())) {
            System.out.println("ไม่กรอก");
        } else {
            search();
        }
    }//GEN-LAST:event_bt_seActionPerformed

    private void bt_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_allActionPerformed
        // TODO add your handling code here:

        searchAll();
        txtSearch.setText("");
    }//GEN-LAST:event_bt_allActionPerformed

    private void combo_levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_levelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_levelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormManageEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addemp;
    private javax.swing.JButton bt_all;
    private javax.swing.JButton bt_del;
    private javax.swing.JButton bt_edit;
    private javax.swing.JButton bt_se;
    private javax.swing.JComboBox<String> combo_level;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelShowDate;
    private javax.swing.JLabel labelShowTime;
    private javax.swing.JPanel line;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBikeInfo;
    private javax.swing.JMenu menuCusInfo;
    private javax.swing.JMenu menuEmployeeInfo;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuMainMenu;
    private javax.swing.JMenu menuRentBike;
    private javax.swing.JMenu menuReturnBike;
    private javax.swing.JTable tableEmployee;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void renderTable() {
        List<Employee> employeeList = service.findAllEmployee();
        Iterator<Employee> cursor = employeeList.iterator();

        String[] column = {"ชื่อผู้ใช้งาน", "รหัสผ่าน", "สถานะ"};
        tableEmployee.getTableHeader().setFont(new Font("TH Sarabun New", Font.BOLD, 18));

        model = new DefaultTableModel(column, 0);

        try {
            while (cursor.hasNext()) {
                Employee employee = cursor.next();
                String employeeId = employee.getEmployeeId();
                String employeeRole = employee.getRole();
                String employeePassword = employee.getPassword();
                model.addRow(new Object[]{employeeId, employeePassword, employeeRole});
            }
        } finally {

        }
        tableEmployee.setModel(model);
    }

    public void search() {
        try {
            Employee cursor = service.findEmployeeById(txtSearch.getText());

            String[] column = {"ชื่อผู้ใช้งาน", "รหัสผ่าน", "สถานะ"};
        tableEmployee.getTableHeader().setFont(new Font("TH Sarabun New", Font.BOLD, 18));

            model = new DefaultTableModel(column, 0);
            Employee employee = cursor;
            String employeeId = employee.getEmployeeId();
            String employeeRole = employee.getRole();
            String employeePassword = employee.getPassword();
            model.addRow(new Object[]{employeeId, employeePassword, employeeRole});

            tableEmployee.setModel(model);
        } catch (Exception e) {
            alertMessage("ไม่มีรหัสรถคันนี้อยู่ในระบบ");
            renderTable();
            clear();
        }
    }

    @Override
    public void alertMessage(String message) {
        JLabel label = new JLabel(message);
        label.setFont(new Font("TH Sarabun New", Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "แจ้งเตือน", JOptionPane.DEFAULT_OPTION);

    }

}
