package bikerental;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author firstx
 */
public class FormReturn extends javax.swing.JFrame implements FormTableInterface {

    private final ServiceReturn service;
    private DefaultTableModel model;

    /**
     * Creates new form FormReturn
     */
    public FormReturn() {
        initComponents();
        service = new ServiceReturn();
        renderTable();
        model = (DefaultTableModel) tableBikeRent.getModel();
        showDate();
        showTime();
    }

    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        labelShowDate.setText(s.format(d));

    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                labelShowTime.setText(s.format(d));
            }

        }
        ).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        labelShowTime = new javax.swing.JLabel();
        iconLogo = new javax.swing.JLabel();
        labelShowDate = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        line = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBikeRent = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtRentId = new javax.swing.JTextField();
        txtBikeId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFine = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuMainMenu = new javax.swing.JMenu();
        menuBikeInfo = new javax.swing.JMenu();
        menuCusInfo = new javax.swing.JMenu();
        menuEmployeeInfo = new javax.swing.JMenu();
        menuRentBike = new javax.swing.JMenu();
        menuReturnBike = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("การคืน");
        setResizable(false);

        head.setBackground(new java.awt.Color(255, 255, 255));
        head.setMinimumSize(new java.awt.Dimension(900, 600));
        head.setPreferredSize(new java.awt.Dimension(902, 600));
        head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelName.setFont(new java.awt.Font("TH Sarabun New", 1, 36)); // NOI18N
        labelName.setText("RENTAL CARS");
        head.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        labelShowTime.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        labelShowTime.setText("HH:MM:SS A");
        head.add(labelShowTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        head.add(iconLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        labelShowDate.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        labelShowDate.setText("dd-MM-yyyy");
        head.add(labelShowDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        head.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 900, -1));

        line.setBackground(new java.awt.Color(238, 88, 40));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        head.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 920, -1));

        txtSearch.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        txtSearch.setToolTipText("");
        txtSearch.setName(""); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        head.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 470, 30));

        btnSearch.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnSearch.setText("ค้นหา");
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        head.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 130, 40));

        btnAll.setBackground(new java.awt.Color(255, 255, 255));
        btnAll.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        btnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/all.png"))); // NOI18N
        btnAll.setText("ดูทั้งหมด");
        btnAll.setBorderPainted(false);
        btnAll.setContentAreaFilled(false);
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });
        head.add(btnAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 140, 40));

        tableBikeRent.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        tableBikeRent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBikeRent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBikeRentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBikeRent);

        head.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 780, 230));

        jLabel2.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        jLabel2.setText("รหัสการเช่า-คืน :");
        head.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        txtRentId.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        txtRentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRentIdActionPerformed(evt);
            }
        });
        head.add(txtRentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 190, 33));

        txtBikeId.setEditable(false);
        txtBikeId.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        txtBikeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBikeIdActionPerformed(evt);
            }
        });
        head.add(txtBikeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 190, 33));

        jLabel3.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        jLabel3.setText("รหัสรถ :");
        head.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, -1));

        jLabel4.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        jLabel4.setText("ค่าปรับ :");
        head.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, -1, -1));

        txtFine.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        txtFine.setText("0");
        txtFine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFineActionPerformed(evt);
            }
        });
        head.add(txtFine, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 190, 33));

        btnReturn.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/return.png"))); // NOI18N
        btnReturn.setText("คืนรถ");
        btnReturn.setBorderPainted(false);
        btnReturn.setContentAreaFilled(false);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        head.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 120, 40));

        menuBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 51, 0), 1, true));
        menuBar.setEnabled(false);

        menuMainMenu.setBorder(null);
        menuMainMenu.setText("เมนูหลัก");
        menuMainMenu.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMainMenuMouseClicked(evt);
            }
        });
        menuBar.add(menuMainMenu);

        menuBikeInfo.setBorder(null);
        menuBikeInfo.setText("ข้อมูลรถ");
        menuBikeInfo.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuBikeInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBikeInfoMouseClicked(evt);
            }
        });
        menuBar.add(menuBikeInfo);

        menuCusInfo.setText("ข้อมูลลูกค้า");
        menuCusInfo.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuCusInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCusInfoMouseClicked(evt);
            }
        });
        menuBar.add(menuCusInfo);

        menuEmployeeInfo.setBorder(null);
        menuEmployeeInfo.setText("ข้อมูลพนักงาน");
        menuEmployeeInfo.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuEmployeeInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEmployeeInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuEmployeeInfoMouseEntered(evt);
            }
        });
        menuBar.add(menuEmployeeInfo);

        menuRentBike.setBorder(null);
        menuRentBike.setText("การเช่า");
        menuRentBike.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuRentBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuRentBikeMousePressed(evt);
            }
        });
        menuBar.add(menuRentBike);

        menuReturnBike.setBorder(null);
        menuReturnBike.setText("การคืน");
        menuReturnBike.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuReturnBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuReturnBikeMousePressed(evt);
            }
        });
        menuBar.add(menuReturnBike);

        menuLogout.setBorder(null);
        menuLogout.setText("ออกจากระบบ");
        menuLogout.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuLogoutMousePressed(evt);
            }
        });
        menuBar.add(menuLogout);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if (!isFill(txtSearch.getText())) {
            System.out.println("ไม่กรอก");
        } else {
            search();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        // TODO add your handling code here:
        searchAll();
    }//GEN-LAST:event_btnAllActionPerformed

    private void tableBikeRentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBikeRentMouseClicked
        // TODO add your handling code here:
        int rowIndex = tableBikeRent.getSelectedRow();

        txtRentId.setText(model.getValueAt(rowIndex, 0).toString());
        txtBikeId.setText(model.getValueAt(rowIndex, 1).toString());


    }//GEN-LAST:event_tableBikeRentMouseClicked

    private void txtRentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRentIdActionPerformed

    private void txtBikeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBikeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBikeIdActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        int rowIndex = tableBikeRent.getSelectedRow();
        if (model.getValueAt(rowIndex, 5).toString().equals("คืนแล้ว")) {
            alertMessage("รถคันนี้ไม่ได้ถูกเช่า");
        } else {
            returnBike();
        }
    }//GEN-LAST:event_btnReturnActionPerformed

    private void menuMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMainMenuMouseClicked
        new FormBikeStatus().show();
        dispose();
    }//GEN-LAST:event_menuMainMenuMouseClicked

    private void menuBikeInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBikeInfoMouseClicked
        // TODO add your handling code here:
        new FormManageBike().show();
        dispose();
    }//GEN-LAST:event_menuBikeInfoMouseClicked

    private void menuCusInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCusInfoMouseClicked
        // TODO add your handling code here:
        new FormShowCustomer().show();
        dispose();
    }//GEN-LAST:event_menuCusInfoMouseClicked

    private void menuEmployeeInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEmployeeInfoMouseClicked
        // TODO add your handling code here:
        new FormManageEmployee().show();
        dispose();

    }//GEN-LAST:event_menuEmployeeInfoMouseClicked

    private void menuEmployeeInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEmployeeInfoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEmployeeInfoMouseEntered

    private void menuRentBikeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRentBikeMousePressed
        // TODO add your handling code here:
        new FormRent().show();
        dispose();
    }//GEN-LAST:event_menuRentBikeMousePressed

    private void menuReturnBikeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReturnBikeMousePressed
        new FormReturn().show();
        dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_menuReturnBikeMousePressed

    private void menuLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMousePressed

        // TODO add your handling code here:*/
    }//GEN-LAST:event_menuLogoutMousePressed

    private void txtFineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFineActionPerformed

    public void returnBike() {
        int rowIndex = tableBikeRent.getSelectedRow();

        if (isFieldAllFill() && txtFine.getText().matches("[0-9]+")) {
            String invoiceId = model.getValueAt(rowIndex, 0).toString();
            String bikeId = model.getValueAt(rowIndex, 1).toString();
            String status = model.getValueAt(rowIndex, 5).toString();
            Float fine = Float.parseFloat(txtFine.getText());
            if (service.returnInvoice(invoiceId, bikeId, status, fine)) {
                alertMessage("คืนรถสำเร็จ");
                renderTable();
                clear();
            }
        } else {
            alertMessage("กรุณากรอกข้อมูลให้ครบถ้วน");
        }
    }

    public void clear() {
        txtBikeId.setText("");
        txtRentId.setText("");
        txtSearch.setText("");
    }

    public boolean isFill(String field) {
        return !field.equals("");
    }

    public boolean isFieldAllFill() {
        return isFill(txtBikeId.getText())
                && isFill(txtFine.getText())
                && isFill(txtRentId.getText());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormReturn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel head;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelShowDate;
    private javax.swing.JLabel labelShowTime;
    private javax.swing.JPanel line;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBikeInfo;
    private javax.swing.JMenu menuCusInfo;
    private javax.swing.JMenu menuEmployeeInfo;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuMainMenu;
    private javax.swing.JMenu menuRentBike;
    private javax.swing.JMenu menuReturnBike;
    private javax.swing.JTable tableBikeRent;
    private javax.swing.JTextField txtBikeId;
    private javax.swing.JTextField txtFine;
    private javax.swing.JTextField txtRentId;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void renderTable() {
        List<Invoice> invoiceList = service.findAllInvoice();
        Iterator<Invoice> cursor = invoiceList.iterator();

        String[] column = {"รหัสการเช่า-คืน", "รหัสรถ", "วันที่เช่า", "วันที่คืน", "วันที่คืนจริง", "สถานะ"};
        tableBikeRent.getTableHeader().setFont(new Font("TH Sarabun New", Font.BOLD, 18));

        DefaultTableModel model = new DefaultTableModel(column, 0);

        try {
            while (cursor.hasNext()) {
                Invoice invoice = cursor.next();
                String InvoiceId = invoice.getInvoiceId();
                String BikeId = invoice.getBikeId();
                String DateRent = invoice.getDateRent();
                String DateReturn = invoice.getDateReturn();
                String DateReturnReal = invoice.getDateReturnReal();
                String Status = invoice.getStatus();
                model.addRow(new Object[]{InvoiceId, BikeId, DateRent, DateReturn, DateReturnReal, Status});
            }
        } finally {

        }
        tableBikeRent.setModel(model);
    }

    private void search() {
        if (isFill(txtSearch.getText())) {
            try {
                Invoice cursor = service.findInvoiceById(txtSearch.getText());

                String[] column = {"รหัสการเช่า-คืน", "รหัสรถ", "วันที่เช่า", "วันที่คืน", "วันที่คืนจริง", "สถานะ"};
                tableBikeRent.getTableHeader().setFont(new Font("TH Sarabun New", Font.BOLD, 18));

                model = new DefaultTableModel(column, 0);
                Invoice invoice = cursor;
                String InvoiceId = invoice.getInvoiceId();
                String BikeId = invoice.getBikeId();
                String DateRent = invoice.getDateRent();
                String DateReturn = invoice.getDateReturn();
                String DateReturnReal = invoice.getDateReturnReal();
                String Status = invoice.getStatus();
                model.addRow(new Object[]{InvoiceId, BikeId, DateRent, DateReturn, DateReturnReal, Status});

                tableBikeRent.setModel(model);
            } catch (Exception e) {
                alertMessage("ไม่พบรายการเช่า-คืนนี้ในระบบ");
                renderTable();
                txtSearch.setText("");
                clear();
            }
        } else {
            alertMessage("กรุณากรอกรหัสการเช่า-คืนรถ");
        }
    }

    private void searchAll() {
        renderTable();
        txtSearch.setText("");
    }

    @Override
    public void alertMessage(String message) {
        JLabel label = new JLabel(message);
        label.setFont(new Font("TH Sarabun New", Font.BOLD, 18));
        JOptionPane.showMessageDialog(null, label, "แจ้งเตือน", JOptionPane.DEFAULT_OPTION);
    }
}
