/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bikerental;

/**
 *
 * @author firstx
 */
public class FromManageBike extends javax.swing.JFrame {

    /**
     * Creates new form FromManageBike
     */
    public FromManageBike() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_moter = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tx_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bt_add = new javax.swing.JButton();
        bt_del = new javax.swing.JButton();
        tx_prov = new javax.swing.JTextField();
        bt_get1 = new javax.swing.JButton();
        tx_se = new javax.swing.JTextField();
        bt_se = new javax.swing.JButton();
        bt_all = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        head = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tx_time = new javax.swing.JLabel();
        tx_Date = new javax.swing.JLabel();
        line = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuMainMenu = new javax.swing.JMenu();
        menuBikeInfo = new javax.swing.JMenu();
        menuCusInfo = new javax.swing.JMenu();
        menuRentBike = new javax.swing.JMenu();
        menuReturnBike = new javax.swing.JMenu();
        menuIncome = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(840, 330));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_moter.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        tb_moter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_moter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_moterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_moter);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 780, 200));

        jLabel2.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        jLabel2.setText("รหัสรถ :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        tx_id.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        tx_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx_idKeyReleased(evt);
            }
        });
        jPanel1.add(tx_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 157, -1));

        jLabel6.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        jLabel6.setText("สถานะ :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        bt_add.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        bt_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        bt_add.setText("เพิ่ม");
        bt_add.setBorderPainted(false);
        bt_add.setContentAreaFilled(false);
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });
        jPanel1.add(bt_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, -1));

        bt_del.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        bt_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        bt_del.setText("ลบ");
        bt_del.setBorderPainted(false);
        bt_del.setContentAreaFilled(false);
        bt_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_delActionPerformed(evt);
            }
        });
        jPanel1.add(bt_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        tx_prov.setEditable(false);
        tx_prov.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        tx_prov.setText("           ว่าง");
        tx_prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_provActionPerformed(evt);
            }
        });
        jPanel1.add(tx_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 160, -1));

        bt_get1.setFont(new java.awt.Font("DB Narai X", 0, 18)); // NOI18N
        bt_get1.setForeground(new java.awt.Color(255, 51, 51));
        bt_get1.setText("ล้างข้อมูล");
        bt_get1.setBorder(null);
        bt_get1.setBorderPainted(false);
        bt_get1.setContentAreaFilled(false);
        bt_get1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_get1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_get1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        tx_se.setFont(new java.awt.Font("DB Narai X", 0, 18)); // NOI18N
        tx_se.setToolTipText("");
        tx_se.setName(""); // NOI18N
        tx_se.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_seActionPerformed(evt);
            }
        });
        jPanel1.add(tx_se, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 450, 30));

        bt_se.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        bt_se.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        bt_se.setText("ค้นหา");
        bt_se.setBorderPainted(false);
        bt_se.setContentAreaFilled(false);
        bt_se.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_seActionPerformed(evt);
            }
        });
        jPanel1.add(bt_se, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 100, 40));

        bt_all.setBackground(new java.awt.Color(255, 255, 255));
        bt_all.setFont(new java.awt.Font("DB Narai X", 0, 24)); // NOI18N
        bt_all.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/all.png"))); // NOI18N
        bt_all.setText("ดูทั้งหมด");
        bt_all.setBorderPainted(false);
        bt_all.setContentAreaFilled(false);
        bt_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_allActionPerformed(evt);
            }
        });
        jPanel1.add(bt_all, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 120, 40));

        jLabel10.setFont(new java.awt.Font("DB Narai X", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*กรอกไอดีรถที่ต้องการค้นหา");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 890, 400));

        head.setBackground(new java.awt.Color(255, 255, 255));
        head.setPreferredSize(new java.awt.Dimension(902, 600));
        head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("DB Narai X", 1, 36)); // NOI18N
        jLabel9.setText("RENTAL CARS");
        head.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/R (1).png"))); // NOI18N
        head.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 88, 72));

        tx_time.setFont(new java.awt.Font("DB Narai X", 1, 18)); // NOI18N
        tx_time.setText("HH:MM:SS A");
        head.add(tx_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        tx_Date.setFont(new java.awt.Font("DB Narai X", 1, 18)); // NOI18N
        tx_Date.setText("dd-MM-yyyy");
        head.add(tx_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1015, 90));

        line.setBackground(new java.awt.Color(238, 88, 40));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1035, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        menuBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 51, 0), 1, true));
        menuBar.setEnabled(false);

        menuMainMenu.setBorder(null);
        menuMainMenu.setText("เมนูหลัก");
        menuMainMenu.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMainMenuMouseClicked(evt);
            }
        });
        menuBar.add(menuMainMenu);

        menuBikeInfo.setBorder(null);
        menuBikeInfo.setText("ข้อมูลรถ");
        menuBikeInfo.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuBar.add(menuBikeInfo);

        menuCusInfo.setText("ข้อมูลลูกค้า");
        menuCusInfo.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuBar.add(menuCusInfo);

        menuRentBike.setBorder(null);
        menuRentBike.setText("การเช่า");
        menuRentBike.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuRentBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuRentBikeMousePressed(evt);
            }
        });
        menuBar.add(menuRentBike);

        menuReturnBike.setBorder(null);
        menuReturnBike.setText("การคืน");
        menuReturnBike.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuReturnBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuReturnBikeMousePressed(evt);
            }
        });
        menuBar.add(menuReturnBike);

        menuIncome.setBorder(null);
        menuIncome.setText("รายได้");
        menuIncome.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuBar.add(menuIncome);

        menuLogout.setBorder(null);
        menuLogout.setText("ออกจากระบบ");
        menuLogout.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuLogoutMousePressed(evt);
            }
        });
        menuBar.add(menuLogout);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_moterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_moterMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tb_moter.getModel();
        int rowIndex = tb_moter.getSelectedRow();

        tx_id.setText(model.getValueAt(rowIndex, 0).toString());
        tx_brand.setText(model.getValueAt(rowIndex, 1).toString());
        tx_license.setText(model.getValueAt(rowIndex, 4).toString());
        tx_prov.setText(model.getValueAt(rowIndex, 5).toString());
        tx_gen.setText(model.getValueAt(rowIndex, 2).toString());
        tx_color.setText(model.getValueAt(rowIndex, 3).toString());
    }//GEN-LAST:event_tb_moterMouseClicked

    private void tx_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_idKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_idKeyReleased

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:
        try {
            BasicDBObject whereQuery = new BasicDBObject();
            whereQuery.put("ID", tx_id.getText());
            DBCursor cursor = coll.find(whereQuery);
            boolean ck = false; //ไว้เช็คว่าซ้ำไหม
            while (cursor.hasNext()) {
                JLabel text = new JLabel("มีรหัสรถนี้อยู่ในระบบแล้ว");
                text.setFont(new Font("TH Sarabun New", Font.BOLD, 18));
                JOptionPane.showMessageDialog(this, text, "แจ้งเตือน", JOptionPane.WARNING_MESSAGE);
                clear();
                ck = true;   //ถ้าซ้ำให้เป็นจริง
                break;
            }
            if (!ck) { //ถ้าไม่ซ้ำให้เพิ่มเข้าไป
                Insert();
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_bt_addActionPerformed

    private void bt_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_delActionPerformed
        // TODO add your handling code here:
        if (tx_id.getText().equals("")) {
            JLabel text = new JLabel("กรุณากรอก ID รถจักรยานยนต์");
            text.setFont(new Font("TH Sarabun New", Font.BOLD, 18));
            JOptionPane.showMessageDialog(this, text, "แจ้งเตือน", JOptionPane.WARNING_MESSAGE);
        } else {
            Delete();
        }
    }//GEN-LAST:event_bt_delActionPerformed

    private void bt_get1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_get1ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_bt_get1ActionPerformed

    private void tx_seActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_seActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_seActionPerformed

    private void bt_seActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_seActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_bt_seActionPerformed

    private void bt_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_allActionPerformed
        // TODO add your handling code here:
        showData();
        tx_se.setText("");
    }//GEN-LAST:event_bt_allActionPerformed

    private void menuMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMainMenuMouseClicked
        // TODO add your handling code here:
        new FormMenuMain().show();
        dispose();
    }//GEN-LAST:event_menuMainMenuMouseClicked

    private void menuRentBikeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRentBikeMousePressed
        // TODO add your handling code here:
        new FormRent().show();
        dispose();
    }//GEN-LAST:event_menuRentBikeMousePressed

    private void menuReturnBikeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReturnBikeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuReturnBikeMousePressed

    private void menuLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMousePressed

        // TODO add your handling code here:*/
    }//GEN-LAST:event_menuLogoutMousePressed

    private void tx_provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_provActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_provActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromManageBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromManageBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromManageBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromManageBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromManageBike().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_all;
    private javax.swing.JButton bt_del;
    private javax.swing.JButton bt_get1;
    private javax.swing.JButton bt_se;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel line;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBikeInfo;
    private javax.swing.JMenu menuCusInfo;
    private javax.swing.JMenu menuIncome;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuMainMenu;
    private javax.swing.JMenu menuRentBike;
    private javax.swing.JMenu menuReturnBike;
    private javax.swing.JTable tb_moter;
    private javax.swing.JLabel tx_Date;
    private javax.swing.JTextField tx_id;
    private javax.swing.JTextField tx_prov;
    private javax.swing.JTextField tx_se;
    private javax.swing.JLabel tx_time;
    // End of variables declaration//GEN-END:variables
}
